version: '3.3'

services:
  db:
    image: mysql:8.0.15
    restart: always
    environment:
      MYSQL_DATABASE: '$MYSQL_DATABASE'
      MYSQL_USER: '$MYSQL_USER'
      MYSQL_PASSWORD: '$MYSQL_PASSWORD'
      MYSQL_ROOT_PASSWORD: '$MYSQL_ROOT_PASSWORD'
    expose:
      - "3306"
    volumes:
      - ./data:/var/lib/mysql
  ktor-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: '$MYSQL_DATABASE'
      MYSQL_USER: '$MYSQL_USER'
      MYSQL_PASSWORD: '$MYSQL_PASSWORD'